apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-buddy-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: study-buddy-ai
  template:
    metadata:
      labels:
        app: study-buddy-ai
    spec:
      containers:
      - name: study-buddy-ai
        image: prathap0703/studybuddy:latest   
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-api-secret
              key: GROQ_API_KEY
